# Generated by Django 5.2.14 on 2026-05-21 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequestFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('allowed_extensions', models.CharField(help_text='Comma-separated extensions, e.g., pdf,docx,xlsx', max_length=200)),
                ('max_file_size_mb', models.PositiveIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'project request file type',
                'verbose_name_plural': 'project request file types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'project request type',
                'verbose_name_plural': 'project request types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'request number sequence',
                'verbose_name_plural': 'request number sequences',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDepartmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('can_receive_project_requests', models.BooleanField(default=True)),
                ('allow_staff_claim', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_dept_profile', to='accounts.department')),
            ],
            options={
                'verbose_name': 'project department profile',
                'verbose_name_plural': 'project department profiles',
                'ordering': ['display_order', 'department__dept_code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, help_text='Auto-generated request number (e.g. PR-2026-0001)', max_length=30, null=True, unique=True)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'P1 - Critical'), (2, 'P2 - High'), (3, 'P3 - Medium'), (4, 'P4 - Low'), (5, 'P5 - Minimal')], null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWING', 'Reviewing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_summary', models.TextField(blank=True, default='')),
                ('business_problem', models.TextField(blank=True, default='')),
                ('business_scope', models.TextField(blank=True, default='')),
                ('technical_scope', models.TextField(blank=True, default='')),
                ('in_scope', models.TextField(blank=True, default='')),
                ('out_of_scope', models.TextField(blank=True, default='')),
                ('expected_deliverables', models.TextField(blank=True, default='')),
                ('acceptance_criteria', models.TextField(blank=True, default='')),
                ('affected_systems', models.TextField(blank=True, default='')),
                ('customer', models.CharField(blank=True, default='', max_length=255)),
                ('etd', models.DateField(blank=True, null=True)),
                ('hours_estimate', models.CharField(blank=True, default='', max_length=50)),
                ('project_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_project_requests', to='accounts.department')),
                ('request_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_project_requests', to='accounts.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requests', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_requests.projectrequesttype')),
            ],
            options={
                'verbose_name': 'project request',
                'verbose_name_plural': 'project requests',
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_requests/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='project_requests.projectrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_project_request_files', to=settings.AUTH_USER_MODEL)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_requests.projectrequestfiletype')),
            ],
            options={
                'verbose_name': 'project request attachment',
                'verbose_name_plural': 'project request attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequestActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DRAFT_CREATED', 'Draft Created'), ('SUBMITTED', 'Submitted'), ('APPROVAL_CREATED', 'Approval Task Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ADDITIONAL_APPROVAL_REQUESTED', 'Additional Approval Requested'), ('ASSIGNED', 'Assigned'), ('CLAIMED', 'Claimed'), ('STARTED', 'Started'), ('PUT_ON_HOLD', 'Put on Hold'), ('RESUMED', 'Resumed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('COMMENTED', 'Commented'), ('FILE_ATTACHED', 'File Attached')], max_length=40)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_request_actions', to=settings.AUTH_USER_MODEL)),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='project_requests.projectrequest')),
            ],
            options={
                'verbose_name': 'project request activity log',
                'verbose_name_plural': 'project request activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_request', '-created_at'], name='pr_log_idx_pr_created'), models.Index(fields=['action_type'], name='pr_log_idx_action'), models.Index(fields=['actor'], name='pr_log_idx_actor')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequestApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REQUEST_DEPT_MANAGER', 'Request Department Manager'), ('PROJECT_DEPT_MANAGER', 'Project Department Manager'), ('PROJECT_DEPT_VP', 'Project Department VP')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_project_approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_approval_tasks', to='accounts.department')),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='project_requests.projectrequest')),
            ],
            options={
                'verbose_name': 'project approval task',
                'verbose_name_plural': 'project approval tasks',
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project_request', 'department', 'role'), name='unique_project_approval_task_per_role_dept')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_project_requests', to=settings.AUTH_USER_MODEL)),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='project_requests.projectrequest')),
            ],
            options={
                'verbose_name': 'project request assignment',
                'verbose_name_plural': 'project request assignments',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project_request', 'assigned_to'), name='unique_active_assignment_per_user')],
            },
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['status'], name='pr_idx_status'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['requester'], name='pr_idx_requester'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['request_department'], name='pr_idx_req_dept'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['project_department'], name='pr_idx_proj_dept'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['request_no'], name='pr_idx_request_no'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['needed_by_date'], name='pr_idx_needed_by'),
        ),
    ]
