# Generated by Django 5.2.14 on 2026-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='request_no',
            field=models.CharField(blank=True, help_text='Auto-generated request number, e.g. PRJ-2026-000001', max_length=30, null=True, unique=True),
        ),
    ]
