"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v#li0l03lzpb9r*qf1w*e^ukk#@)jb=jcdglmew36lwm4+0pvb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'accounts',
    'project_requests',
    'external_auth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# -----------------------------------------------------------------------------
# FoxPro External Authentication Settings (Phase 4F)
# -----------------------------------------------------------------------------

# Signature mode for FoxPro launch URL validation
# Currently only 'legacy_v2' is supported for pilot
# Any other value will cause launch to be rejected
FOXPRO_SIGNATURE_MODE = 'legacy_v2'

# Shared secret for FoxPro v2 signature algorithm
# IMPORTANT: Generate a strong random secret and store securely
# The secret should be at least 32 characters long
# Replace with actual secret before pilot deployment
FOXPRO_V2_SECRET = 'INTERNAL-SECRET-32PLUS'

# Maximum age of launch timestamp in seconds (v2 pilot: 15 seconds)
# This prevents replay attacks by rejecting stale URLs
FOXPRO_LAUNCH_MAX_AGE_SECONDS = 15

# Timezone for parsing FoxPro timestamp (d=YYYYMMDDHHMMSS)
# FoxPro generates timestamps in local/server time
# Parse as naive datetime in this timezone, then convert to aware datetime for comparison
FOXPRO_LAUNCH_TIMEZONE = 'America/Los_Angeles'

# IP allowlist for FoxPro launch requests
# Uses CIDR notation for subnet ranges (e.g., '10.0.0.0/8' for internal network)
# Empty list means no IP restriction (not recommended for production)
# Current deployment runs from local workstations, so allow internal subnet
FOXPRO_ALLOWED_IPS = [
    '127.0.0.1',           # Localhost for testing
    '::1',                 # IPv6 localhost for testing
]

# Whether to trust X-Forwarded-For header for client IP
# If False (default), uses REMOTE_ADDR only (more secure for single-server setup)
# If True, uses X-Forwarded-For (only use if behind a trusted proxy)
FOXPRO_TRUST_X_FORWARDED_FOR = False

# Allowed return named routes after successful FoxPro launch
# Only named routes in this list are allowed for redirect
# Do not include admin routes in pilot scope
FOXPRO_ALLOWED_RETURN_PATHS = [
    'project_requests:dashboard',  # Default and pilot-allowed
    'project_requests:index',        # Pilot-allowed
]
