# Generated by Django 5.2.14 on 2026-05-28 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoxproLaunchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Employee short name from launch URL (identity hint only)', max_length=150)),
                ('long_name', models.CharField(blank=True, default='', help_text='Employee long name from launch URL (display/audit only)', max_length=255)),
                ('dept_code', models.CharField(blank=True, default='', help_text='Department code from launch URL', max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text='Employee title from launch URL', max_length=150)),
                ('legacy_access_level', models.CharField(blank=True, default='', help_text='FoxPro o param - audit only, NOT used for Django authorization', max_length=10)),
                ('return_path', models.CharField(blank=True, default='', help_text='Requested return path (named route)', max_length=255)),
                ('nonce_hash', models.CharField(help_text='SHA-256 hash of nonce from launch URL (for audit)', max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('signature_valid', models.BooleanField(default=False, help_text='Signature passed validation')),
                ('timestamp_valid', models.BooleanField(default=False, help_text='Timestamp within max age')),
                ('success', models.BooleanField(default=False, help_text='Launch succeeded (user found, session created)')),
                ('failure_reason', models.CharField(blank=True, choices=[('IP_BLOCKED', 'IP Blocked'), ('MISSING_PARAMS', 'Missing Parameters'), ('INVALID_VERSION', 'Invalid Version'), ('INVALID_TIMESTAMP_FORMAT', 'Invalid Timestamp Format'), ('TIMESTAMP_EXPIRED', 'Timestamp Expired'), ('INVALID_SIGNATURE', 'Invalid Signature'), ('NONCE_REUSED', 'Nonce Reused'), ('USER_NOT_FOUND', 'User Not Found'), ('USER_INACTIVE', 'User Inactive'), ('DEPT_NOT_FOUND', 'Department Not Found'), ('DEPT_MEMBERSHIP_MISSING', 'Department Membership Missing'), ('UNKNOWN_ERROR', 'Unknown Error')], default='', help_text='Short failure reason code', max_length=50)),
                ('raw_params', models.JSONField(blank=True, help_text='Snapshot of all decoded params (secret not included)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Mapped Django user (null if no match)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foxpro_launch_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_auth_foxpro_launch_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoxproLaunchNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce_hash', models.CharField(help_text='SHA-256 hash of the nonce (unique constraint prevents replay)', max_length=64, unique=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='IP that first presented this nonce', null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('launch_attempt', models.OneToOneField(blank=True, help_text='Link to successful launch attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonce_reserved', to='external_auth.foxprolaunchattempt')),
            ],
            options={
                'db_table': 'external_auth_foxpro_launch_nonce',
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='foxprolaunchattempt',
            name='nonce_reservation',
            field=models.OneToOneField(blank=True, help_text='Link to nonce reservation record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt', to='external_auth.foxprolaunchnonce'),
        ),
        migrations.AddIndex(
            model_name='foxprolaunchnonce',
            index=models.Index(fields=['first_seen_at'], name='idx_nonce_time'),
        ),
        migrations.AddIndex(
            model_name='foxprolaunchattempt',
            index=models.Index(fields=['nonce_hash'], name='idx_attempt_nonce'),
        ),
        migrations.AddIndex(
            model_name='foxprolaunchattempt',
            index=models.Index(fields=['short_name', 'dept_code', 'created_at'], name='idx_attempt_name_dept'),
        ),
        migrations.AddIndex(
            model_name='foxprolaunchattempt',
            index=models.Index(fields=['source_ip', 'created_at'], name='idx_attempt_ip_time'),
        ),
    ]
