# Generated by Django 5.2.14 on 2026-05-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foxprolaunchattempt',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('IP_BLOCKED', 'IP Blocked'), ('MISSING_PARAMS', 'Missing Parameters'), ('INVALID_VERSION', 'Invalid Version'), ('INVALID_TIMESTAMP_FORMAT', 'Invalid Timestamp Format'), ('TIMESTAMP_EXPIRED', 'Timestamp Expired'), ('INVALID_SIGNATURE', 'Invalid Signature'), ('NONCE_REUSED', 'Nonce Reused'), ('UNSUPPORTED_SIGNATURE_MODE', 'Unsupported Signature Mode'), ('USER_NOT_FOUND', 'User Not Found'), ('USER_INACTIVE', 'User Inactive'), ('DEPT_NOT_FOUND', 'Department Not Found'), ('DEPT_MEMBERSHIP_MISSING', 'Department Membership Missing'), ('UNKNOWN_ERROR', 'Unknown Error')], default='', help_text='Short failure reason code', max_length=50),
        ),
    ]
